### ISSUE TITLE
Is it possible to get Real World Coordinates (X,Y,Z) from point on 2 images?

### ISSUE THREAD

**Issue by treecon** [Eric-Canas/Homography.js#3]
Hi,

I have 2 images and some points with known pixel coordinates (x, y) in both images. Is it possible to get the World Coordinates (X, Y, Z) on a given reference system, if I know:
- the rotation of the camera on both images (yaw, pitch, roll)
- the World Coordinates of the camera of both images (X, Y, Z)
?

Thank you in advance!

**Comment by Eric-Canas** [comment]
Hi, 

Sorry for the late reply. 

I can't help too much with that because I'm not really an expert. All my knowledge about _Euler Angles_ and _Real World Coordinates Transforms_, vanished 3 or 4 years ago when I stopped using them.

There are only a few things that I can say about that.

- If you can go from these Euler Angles to Quaternions, it is usually preferable to avoid [Gimbal Lock](https://en.wikipedia.org/wiki/Gimbal_lock#The_quaternion_solution)
- If you are planning to get the distance between the camera and some objects in the image. You will only be able to do it if you can detect them with some _ML_ or _Computer Vision_ method, and you know beforehand both: that they have a fixed real-world measures and the intrinsics of your camera (sensor shape, physical pixel size and focal length of your lens). In that concrete case, you can estimate it with the [Thin Lens Equation](http://hyperphysics.phy-astr.gsu.edu/hbase/geoopt/lenseq.html) 
- I have found this [StackOverflow Answer](https://stackoverflow.com/questions/17210424/3d-camera-coordinates-to-world-coordinates-change-of-basis/17213939#17213939) that could help you.

**Comment by treecon** [comment]
Hi! Thank you very much for all provided info.
